require 'tempfile'
require 'stringio'

module Linecook
  class Package
    # The package environment
    attr_reader :env

    # A registry of (target_path, source_path) pairs recording what files
    # are included in the package.
    attr_reader :registry

    # A hash of the default export options.  These are merged with the export
    # opts for a given target path.
    attr_reader :default_export_options

    # A hash of (target_path, Hash) pairs identifing export options for a
    # target path.  See on_export.
    attr_reader :export_option_overrides

    # A hash of callbacks registered with self
    attr_reader :callbacks

    # An array of tempfiles generated by self (used to cleanup on close)
    attr_reader :tempfiles

    def initialize(env={})
      @env = env
      @registry = {}
      @default_export_options  = {}
      @export_option_overrides = {}
      @callbacks = {}
      @tempfiles = []
    end

    # Resolves a source (ex a StringIO or Tempfile) to a source path by
    # calling `source.path`, which should return a String pathname. If the
    # source does not respond to path, then the source should be the pathname.
    # Returns the expanded source path.
    def resolve_source_path(source)
      source_path = source.respond_to?(:path) ? source.path : source
      unless source_path.kind_of?(String)
        raise "could not resolve source to a path: #{source.inspect}"
      end
      File.expand_path(source_path)
    end

    # Registers the source to the target_path.  The source is first resolved
    # to a source path using resolve_source_path.
    def add(target_path, source, options={})
      source_path = resolve_source_path(source)

      if current = registry[target_path]
        unless current == source_path
          raise "already registered: #{target_path.inspect} (#{current.inspect})"
        end
      else
        registry[target_path] = source_path
      end

      on_export(target_path, options)

      source
    end

    # Removes a target path from the registry.
    def rm(target_path)
      registry.delete(target_path)
    end

    # Removes all target paths that reference a source in the registry.  The
    # source is resolved to a source path using resolve_source_path in the
    # same way as add.
    def unregister(source)
      path = resolve_source_path(source)
      registry.delete_if do |target_path, source_path|
        path == source_path
      end
    end

    # Returns the source path registered to target path, or nil if the target
    # path is not registered.
    def source_path(target_path)
      registry[target_path]
    end

    # Returns an array of target paths that register the source.  The source
    # is resolved to a source path using resolve_source_path.
    def target_paths(source)
      source_path = resolve_source_path(source)

      target_paths = []
      registry.each_pair do |target_path, current|
        if current == source_path
          target_paths << target_path
        end
      end

      target_paths
    end

    # Returns the content for a target, as registered in self.  Returns nil if
    # the target is not registered.
    def content(target_path, length=nil, offset=nil)
      path = registry[target_path]
      path ? File.read(path, length, offset) : nil
    end

    def callback(name)
      callbacks[name] ||= StringIO.new
    end

    # Generates a tempfile for the target path and adds it to self. As
    # with register, the target_name will be incremented as needed.  Returns
    # the open tempfile.
    def tempfile(target_name, options={})
      tempfile = Tempfile.new File.basename(target_name)

      add target_name, tempfile
      on_export target_name, {:move => true}.merge(options)

      tempfiles << tempfile
      tempfile
    end

    # Closes all tempfiles and callbacks and returns self.
    def close
      (tempfiles + callbacks.values).each do |io|
        io.close unless io.closed?
      end
      self
    end

    # Sets export options for the target path.  Available options include:
    #
    #   Option    Description
    #   :move     When set to true the target source will be moved into place
    #             rather than copied (the default)
    #   :mode     Sets the mode of the target to the option value
    #
    def on_export(target_path, options={})
      export_option_overrides[target_path] = options
    end

    # Returns a hash of the export options for a target path, equivalent to
    # the default_export_options merged with any overriding options set for
    # the target.
    def export_options(target_path)
      overrides = export_option_overrides[target_path] || {}
      default_export_options.merge(overrides)
    end

    def export(dir)
      close

      registry.each_key do |target_path|
        export_path = File.join(dir, target_path)
        source_path = registry[target_path]
        options     = export_options(target_path)

        if source_path != export_path
          export_dir = File.dirname(export_path)
          FileUtils.mkdir_p(export_dir)

          if options[:move]
            FileUtils.mv(source_path, export_path)
          else
            FileUtils.cp(source_path, export_path)
          end
        end

        if mode = options[:mode]
          FileUtils.chmod(mode, export_path)
        end

        registry[target_path] = export_path
      end

      registry
    end
  end
end